movies = [
    {"title": "Interstellar", "genre": "scifi", "year": 2014, "rating": 8.7, "duration": 169, "mood": "thrilling"},
    {"title": "Inception", "genre": "scifi", "year": 2010, "rating": 8.8, "duration": 148, "mood": "thrilling"},
    {"title": "Everything Everywhere All at Once", "genre": "scifi", "year": 2022, "rating": 7.7, "duration": 139, "mood": "funny"},
    {"title": "The Dark Knight", "genre": "action", "year": 2008, "rating": 9.0, "duration": 152, "mood": "thrilling"},
    {"title": "Avengers: Endgame", "genre": "action", "year": 2019, "rating": 8.4, "duration": 181, "mood": "thrilling"},
    {"title": "The Grand Budapest Hotel", "genre": "comedy", "year": 2014, "rating": 8.1, "duration": 99, "mood": "funny"},
    {"title": "Toy Story", "genre": "comedy", "year": 1995, "rating": 8.3, "duration": 81, "mood": "funny"},
    {"title": "Spider-Man: Into the Spider-Verse", "genre": "action", "year": 2018, "rating": 8.4, "duration": 117, "mood": "thrilling"},
    {"title": "The Incredibles", "genre": "action", "year": 2004, "rating": 8.0, "duration": 115, "mood": "funny"},
    {"title": "Spirited Away", "genre": "drama", "year": 2001, "rating": 8.6, "duration": 125, "mood": "touching"},
    {"title": "Titanic", "genre": "romance", "year": 1997, "rating": 7.9, "duration": 194, "mood": "touching"},
    {"title": "Back to the Future", "genre": "scifi", "year": 1985, "rating": 8.5, "duration": 116, "mood": "funny"},
    {"title": "The Matrix", "genre": "scifi", "year": 1999, "rating": 8.7, "duration": 136, "mood": "thrilling"},
    {"title": "Forrest Gump", "genre": "romance", "year": 1994, "rating": 8.8, "duration": 142, "mood": "touching"},
    {"title": "The Truman Show", "genre": "comedy", "year": 1998, "rating": 8.2, "duration": 103, "mood": "touching"},
    {"title": "The Shawshank Redemption", "genre": "drama", "year": 1994, "rating": 9.3, "duration": 142, "mood": "touching"},
    {"title": "Fight Club", "genre": "action", "year": 1999, "rating": 8.8, "duration": 139, "mood": "thrilling"},
    {"title": "Fate/stay night: Unlimited Blade Works", "genre": "fantasy", "year": 2010, "rating": 7.4, "duration": 105, "mood": "thrilling"},
    {"title": "Fate/stay night: Heaven's Feel I. presage flower", "genre": "fantasy", "year": 2017, "rating": 7.4, "duration": 120, "mood": "thrilling"},
    {"title": "Fate/stay night: Heaven's Feel II. lost butterfly", "genre": "fantasy", "year": 2019, "rating": 8.0, "duration": 117, "mood": "thrilling"},
    {"title": "Fate/stay night: Heaven's Feel III. spring song", "genre": "fantasy", "year": 2020, "rating": 8.2, "duration": 122, "mood": "thrilling"},
    {"title": "Kara no Kyoukai: The Garden of Sinners", "genre": "thriller", "year": 2007, "rating": 7.5, "duration": 50, "mood": "thrilling"},
    {"title": "Akira", "genre": "scifi", "year": 1988, "rating": 8.0, "duration": 124, "mood": "thrilling"},
    {"title": "Perfect Blue", "genre": "thriller", "year": 1997, "rating": 8.0, "duration": 81, "mood": "thrilling"},
    {"title": "Paprika", "genre": "scifi", "year": 2006, "rating": 7.7, "duration": 90, "mood": "thrilling"},
    {"title": "Howl's Moving Castle", "genre": "romance", "year": 2004, "rating": 8.2, "duration": 119, "mood": "touching"},
    {"title": "Princess Mononoke", "genre": "action", "year": 1997, "rating": 8.3, "duration": 133, "mood": "thrilling"},
    {"title": "Kiki's Delivery Service", "genre": "fantasy", "year": 1989, "rating": 7.8, "duration": 103, "mood": "touching"},
    {"title": "Grave of the Fireflies", "genre": "drama", "year": 1988, "rating": 8.5, "duration": 88, "mood": "touching"},
    {"title": "Ponyo", "genre": "fantasy", "year": 2008, "rating": 7.6, "duration": 101, "mood": "touching"},
    {"title": "The Wind Rises", "genre": "romance", "year": 2013, "rating": 7.8, "duration": 126, "mood": "touching"},
    {"title": "Ghost in the Shell", "genre": "scifi", "year": 1995, "rating": 7.9, "duration": 83, "mood": "thrilling"},
    {"title": "Kung Fu Hustle", "genre": "action", "year": 2004, "rating": 7.7, "duration": 99, "mood": "funny"},
    {"title": "Shaolin Soccer", "genre": "action", "year": 2001, "rating": 7.3, "duration": 87, "mood": "funny"},
    {"title": "The God of Cookery", "genre": "comedy", "year": 1996, "rating": 7.2, "duration": 95, "mood": "funny"},
    {"title": "Rush Hour", "genre": "action", "year": 1998, "rating": 7.0, "duration": 98, "mood": "funny"},
    {"title": "The Green Mile", "genre": "drama", "year": 1999, "rating": 8.6, "duration": 189, "mood": "touching"},
    {"title": "Saving Private Ryan", "genre": "action", "year": 1998, "rating": 8.6, "duration": 169, "mood": "thrilling"},
    {"title": "Rocky", "genre": "action", "year": 1976, "rating": 8.1, "duration": 120, "mood": "touching"},
    {"title": "Police Story", "genre": "action", "year": 1985, "rating": 7.5, "duration": 100, "mood": "thrilling"},
    {"title": "Police Story 2", "genre": "action", "year": 1988, "rating": 7.1, "duration": 101, "mood": "thrilling"},
    {"title": "Project Hail Mary", "genre": "scifi", "year": 2026, "rating": 8.0, "duration": 150, "mood": "thrilling"},
    {"title": "Iron Lung", "genre": "scifi", "year": 2026, "rating": 7.0, "duration": 95, "mood": "thrilling"},
    {"title": "Nope", "genre": "scifi", "year": 2022, "rating": 6.8, "duration": 130, "mood": "thrilling"},
]
#info is taken from imdb ratings btw